### ISSUE TITLE
Olden Tower Ruins / music doesn't play if coming back from Save & Quit in last room

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#49] opened 2020-09-11 14:20 UTC
The music in the last gameplay room doesn't play if you save & quit inside of it.
Submitted by JaThePlayer

**Comment by maddie480** [comment] 2020-10-11 08:05
Duplicate of #272

**Closed as completed by maddie480** 2020-10-11 08:05 UTC
Labels: Visual
