### ISSUE TITLE
Badeline Block Belt berries in pause menu

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#76] opened 2020-09-12 03:44 UTC
One berry does not show up in the pause menu strawberry display: https://discordapp.com/channels/403698615446536203/429775260108324865/754184882418090054
Submitted by The_Cookie_Monster

**Comment by maddie480** [comment] 2020-09-12 07:49
Duplicate of #8

**Closed as completed by maddie480** 2020-09-12 07:49 UTC
Labels: Visual
