### ISSUE TITLE
bobdole gm tutorial

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#185] opened 2020-09-17 00:24 UTC
you can transition left after the second room and the tutorial for the following room will come with you  (originally submitted by jacks) https://clips.twitch.tv/PluckyWealthyHedgehogPermaSmug
Submitted by Marlin

**Comment by maddie480** [comment] 2020-09-17 11:13
Duplicate of #127

**Closed as completed by maddie480** 2020-09-17 11:13 UTC
Labels: Visual
