### ISSUE TITLE
ultra difficult theme

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#115] opened 2020-09-13 11:11 UTC
resetting a speedberry run sets the color theme to default even if it was light theme before (as if anyone actually uses light theme <:snowmadeline:664229627325317161>)
Submitted by tofu

**Comment by maddie480** [comment] 2020-09-13 12:31
duplicate of #82 (the idea is the same, don't store theme in session because theme gets reset when you restart chapter or golden berry restart)

**Closed as completed by maddie480** 2020-09-13 12:31 UTC
Labels: Visual
