### ISSUE TITLE
[Fishtank GM crash]

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#122] opened 2020-09-13 20:14 UTC
[Koko crashes after backtracking from screen 4 to screen 3, Max480 said it's probably a watchtower in wall crash?]
Submitted by Cabob

**Comment by maddie480** [comment] 2020-09-13 20:27
Certainly caused by a watchtower in an exit block in room 3. If you come from the right, the exit block appears right away, and triggers the watchtower-in-wall crash.

**Comment by maddie480** [comment] 2020-09-13 23:59
Now duplicate of #128

**Closed as completed by maddie480** 2020-09-13 23:59 UTC
Labels: Other
