### ISSUE TITLE
Music Speed Triggers in Grandmaster Heartside Not Working

### ISSUE THREAD

**Issue by bissy-bissy-bissy** [iamdadbod/SpringCollab2020Issues#3] opened 2020-09-10 00:13 UTC
Apparently, these triggers trigger the layer of music when standing still inside the triggers? Reported by Thegur90, will need further looking into.

**Comment by max4805** [comment] 2020-09-10 12:00
Duplicated by #18

**Comment by maddie480** [comment] 2020-09-10 15:25
Duplicate of #18

**Closed as completed** 2020-09-10 19:29 UTC
Labels: Bug
