### ISSUE TITLE
Weird standing spot in Major Malfunction

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#336] opened 2020-11-11 14:32 UTC
you can stand here in major malfunction, but you die when you duck
Submitted by DanTKO | CEO Of Haikus

**Comment by tesselslate** [comment] 2020-11-11 17:46
https://cdn.discordapp.com/attachments/753487654435422228/776091999882444870/Screen_Shot_2020-11-11_at_8.30.44_AM.png

Screenshot doesn't copy from discord

**Comment by maddie480** [comment] 2020-11-12 12:17
Duplicate of #337

**Closed as completed by maddie480** 2020-11-12 12:17 UTC
Labels: Gameplay
