### ISSUE TITLE
KoKoDoKo? crash on room transition

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#277] opened 2020-10-01 07:31 UTC
i transitioned from fishtank_03 to fishtank_04, then attempted to go back before the exit block spawned. my game crashed with the attached error. i then reopened the map through the lobby and it had wiped all my progress. i tried to debug back to the end of fishtank_03 to try again and it crashed + wiped my progress again.
Submitted by Bigkahuna

**Comment by maddie480** [comment] 2020-10-04 07:53
Duplicate of #128

**Closed as completed by maddie480** 2020-10-04 07:53 UTC
Labels: Bug
