### ISSUE TITLE
overly precise section in flag 1 EXHS

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#248] opened 2020-09-24 17:36 UTC
the first fish boost in the Electric Exuberance section of the EXHS has incredibly tight timing based on slight variations of timing on the section before it... i i would essentially get three different cycles of cassette blocks seemingly at random
Submitted by Bigkahuna

**Comment by maddie480** [comment] 2020-09-24 17:41
duplicate of #249 (this was submitted by accident)

**Closed as completed by maddie480** 2020-09-24 17:41 UTC
Labels: Gameplay
