### ISSUE TITLE
Cutscene bug in the intro of The Correlation

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#390] opened 2021-07-05 17:57 UTC
If you do a Wavedash and then diagdash to reach the part where it's Theo and you climb until the jumpthrought, the cutscene starts and maddy falls into the void but it doesn't kill her until the cutscene is finished.
Submitted by Renatotheflowey

**Comment by maddie480** [comment] 2021-07-05 18:04
Duplicate of #391

**Closed as completed** 2021-07-05 18:03 UTC
Labels: Gameplay
